/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations, scene } = useGLTF('./model-riging.glb');
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names].play();
  });

  useLayoutEffect(() => {
    scene.traverse((obj) => {
      if (obj.isMesh) {
        obj.material.envMapIntensity = 0.8
      }
    })
  }, [scene])

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload('./model-riging.glb');
