/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations, scene } = useGLTF('https://models.readyplayer.me/64eff5301db75f90dcfd6832.glb');
  const { actions } = useAnimations(animations, group);

  useLayoutEffect(() => {
    scene.traverse((obj) => {
      if (obj.isMesh) {
        obj.material.envMapIntensity = 0.8
      }
    })
  }, [scene])

  return (
    <group {...props} dispose={null}>
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload('https://models.readyplayer.me/64eff5301db75f90dcfd6832.glb');
